### ISSUE TITLE
support Scala 2.12.4

### ISSUE THREAD

**Issue by SethTisue** [OlegYch/multibot#6]
currently multibot is stuck on Scala 2.12.3

on scala/scala Gitter, @OlegYch wrote:

> 2.12.4 somehow breaks multibot, so 2.12.3 will have to do for now
> im not sure what's causing it, probably something specific to multibot
> i'll track it down sooner or later
> otherwise you could just sbt '++2.12.4 run org.multibot.Multibottest' and see it not evaluating scala

**Comment by SethTisue** [comment]
in order to recognize what's incorrect with the 2.12.4 output, I first tried it with 2.12.3. a transcript of my attempt is here: https://gist.github.com/SethTisue/34d34b6cee9fa4988b8b62ff6700f2cb

I don't see Scala code being evaluated anywhere here, so I don't know how to "see it not evaluating scala" when I switch to 2.12.4...?

**Comment by OlegYch** [comment]
@SethTisue it's on https://gitter.im/OlegYch/multibot in dev mode, so that's where you can try it out
